// Generated by Wrangler on Tue Apr 02 2024 08:31:30 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	MICROCMS_API_KEY: string;
	WEBHOOK_SECRET: string;
}
